### ISSUE TITLE
Bilder mit Wischen wechseln

### ISSUE THREAD

**Issue by berkus-b** [inimodo/derh_archive#1]
Es wäre benutzerfreundlicher, wenn man in den Ordnern die Bilder wechseln könnte, indem man seitlich wischt (wie bei der Fotogalerie am Handy). So muss man nicht immer raus und dann das andere Bild auswählen.

**Comment by inimodo** [comment]
Erledigt. Mit Klicken auf das Bild kann das nächste Bild in der Reihe angesehen werden. Die Seite auf die geklickt wird bestimmt die Richtung.
